[package]
name = "jl_amqp_worker"
version = "0.0.1"
edition = "2018"

[dependencies]
# mcai_worker_sdk = { path = "../rs_mcai_worker_sdk" }
lapin-futures = "0.28.4"
log = "0.4.5"
jlrs = "0.4.0"
semver = "^0.9"
serde_json = "^1.0"
