[package]
name = "c_amqp_worker"
version = "0.1.0"
authors = ["Valentin NOEL <valentin.noel@media-io.com>"]
edition = "2018"

[dependencies]
libc = "0.2.65"
amqp_worker = "0.6.0"
log = "0.4.5"
semver = "^0.9"
serde_json = "^1.0"
libloading = "0.5"
