[package]
name = "c_amqp_worker"
version = "0.2.0"
authors = ["Valentin NOEL <valentin.noel@media-io.com>"]
edition = "2018"

[dependencies]
libc = "0.2.66"
amqp_worker = {version = "0.6.0", path = "../rs_amqp_worker"}
log = "0.4.8"
semver = "^0.9"
serde_json = "^1.0"
libloading = "0.5"
