[package]
name = "rs_amqp_worker"
version = "0.1.0"
authors = ["Marc-Antoine Arnaud <arnaud.marcantoine@gmail.com>"]

[dependencies]
reqwest = "0.8.1"
futures = "^0.1"
tokio-core = "= 0.1.13"
lapin-futures = "^0.10"
serde = "^1.0"
serde_json = "^1.0"
